# Generated by Django 4.2.23 on 2025-08-19 19:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('risk_free_rate', models.DecimalField(decimal_places=6, help_text='Tasa libre de riesgo', max_digits=8)),
                ('market_return', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('vix', models.DecimalField(blank=True, decimal_places=6, help_text='Índice de volatilidad VIX', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Data',
                'verbose_name_plural': 'Market Data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del portfolio optimizado', max_length=100)),
                ('optimization_type', models.CharField(choices=[('markowitz', 'Markowitz Mean-Variance'), ('black_litterman', 'Black-Litterman'), ('risk_parity', 'Risk Parity'), ('minimum_variance', 'Minimum Variance'), ('maximum_sharpe', 'Maximum Sharpe Ratio')], max_length=20)),
                ('expected_return', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('volatility', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('optimization_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio Optimization',
                'verbose_name_plural': 'Portfolio Optimizations',
                'ordering': ['-optimization_date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Símbolo bursátil', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Nombre completo de la empresa', max_length=200)),
                ('sector', models.CharField(blank=True, help_text='Sector de la empresa', max_length=100)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Capitalización de mercado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=6, help_text='Peso del stock en el portfolio (0-1)', max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_management.portfoliooptimization')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_management.stock')),
            ],
            options={
                'verbose_name': 'Portfolio Weight',
                'verbose_name_plural': 'Portfolio Weights',
                'unique_together': {('portfolio', 'stock')},
            },
        ),
        migrations.AddField(
            model_name='portfoliooptimization',
            name='stocks',
            field=models.ManyToManyField(through='portfolio_management.PortfolioWeight', to='portfolio_management.stock'),
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow Statement')], max_length=20)),
                ('period_end', models.DateField(help_text='Fecha de fin del período')),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_quarter', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='portfolio_management.stock')),
            ],
            options={
                'verbose_name': 'Financial Statement',
                'verbose_name_plural': 'Financial Statements',
                'ordering': ['-period_end'],
                'unique_together': {('stock', 'statement_type', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('indicator_type', models.CharField(choices=[('sma', 'Simple Moving Average'), ('ema', 'Exponential Moving Average'), ('rsi', 'Relative Strength Index'), ('macd', 'MACD'), ('bollinger_upper', 'Bollinger Band Upper'), ('bollinger_lower', 'Bollinger Band Lower'), ('adx', 'Average Directional Index'), ('stochastic_k', 'Stochastic %K'), ('stochastic_d', 'Stochastic %D')], max_length=20)),
                ('period', models.IntegerField(help_text='Período usado para el cálculo')),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='portfolio_management.stock')),
            ],
            options={
                'verbose_name': 'Technical Indicator',
                'verbose_name_plural': 'Technical Indicators',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date', 'indicator_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('high_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('low_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('adj_close_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio_management.stock')),
            ],
            options={
                'verbose_name': 'Stock Price',
                'verbose_name_plural': 'Stock Prices',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RiskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('var', 'Value at Risk'), ('cvar', 'Conditional Value at Risk'), ('beta', 'Beta'), ('alpha', 'Alpha'), ('sharpe_ratio', 'Sharpe Ratio'), ('sortino_ratio', 'Sortino Ratio'), ('max_drawdown', 'Maximum Drawdown'), ('volatility', 'Volatility')], max_length=20)),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('confidence_level', models.DecimalField(blank=True, decimal_places=4, help_text='Nivel de confianza para VaR/CVaR', max_digits=5, null=True)),
                ('time_horizon', models.IntegerField(blank=True, help_text='Horizonte temporal en días', null=True)),
                ('calculation_date', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='portfolio_management.stock')),
            ],
            options={
                'verbose_name': 'Risk Metric',
                'verbose_name_plural': 'Risk Metrics',
                'ordering': ['-calculation_date'],
                'unique_together': {('stock', 'metric_type', 'calculation_date', 'confidence_level', 'time_horizon')},
            },
        ),
        migrations.CreateModel(
            name='FinancialMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='Nombre de la métrica financiera', max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('financial_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='portfolio_management.financialstatement')),
            ],
            options={
                'verbose_name': 'Financial Metric',
                'verbose_name_plural': 'Financial Metrics',
                'unique_together': {('financial_statement', 'metric_name')},
            },
        ),
    ]
