# Generated by Django 4.2.23 on 2025-08-19 19:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la opción', max_length=100)),
                ('type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], help_text='Tipo de opción', max_length=4)),
                ('style', models.CharField(choices=[('european', 'European'), ('american', 'American')], help_text='Estilo de ejercicio', max_length=8)),
                ('spot', models.DecimalField(decimal_places=6, help_text='Precio actual del activo subyacente', max_digits=15, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('strike', models.DecimalField(decimal_places=6, help_text='Precio de ejercicio', max_digits=15, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('maturity', models.DecimalField(decimal_places=6, help_text='Tiempo hasta vencimiento en años', max_digits=8, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('volatility', models.DecimalField(decimal_places=6, help_text='Volatilidad implícita', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.DecimalField(decimal_places=6, help_text='Tasa libre de riesgo', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('market_price', models.DecimalField(blank=True, decimal_places=6, help_text='Precio de mercado observado', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del portfolio', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción del portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('black_scholes', 'Black-Scholes'), ('binomial', 'Binomial'), ('monte_carlo', 'Monte Carlo')], max_length=20)),
                ('calculated_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('implied_volatility', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('n_steps', models.IntegerField(blank=True, help_text='Número de pasos para modelos binomial/MC', null=True)),
                ('n_simulations', models.IntegerField(blank=True, help_text='Número de simulaciones para MC', null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_results', to='option_pricing.option')),
            ],
            options={
                'verbose_name': 'Resultado de Pricing',
                'verbose_name_plural': 'Resultados de Pricing',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Greeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=8, help_text='Sensibilidad al precio del subyacente', max_digits=15)),
                ('gamma', models.DecimalField(decimal_places=8, help_text='Sensibilidad del delta', max_digits=15)),
                ('vega', models.DecimalField(decimal_places=8, help_text='Sensibilidad a la volatilidad', max_digits=15)),
                ('theta', models.DecimalField(decimal_places=8, help_text='Decay temporal', max_digits=15)),
                ('rho', models.DecimalField(decimal_places=8, help_text='Sensibilidad a la tasa de interés', max_digits=15)),
                ('pricing_model', models.CharField(help_text='Modelo utilizado para el cálculo', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greeks', to='option_pricing.option')),
            ],
            options={
                'verbose_name': 'Greeks',
                'verbose_name_plural': 'Greeks',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Cantidad de contratos (positivo = largo, negativo = corto)', max_digits=15)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, help_text='Precio de entrada de la posición', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option_pricing.option')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='option_pricing.portfolio')),
            ],
            options={
                'verbose_name': 'Posición del Portfolio',
                'verbose_name_plural': 'Posiciones del Portfolio',
                'unique_together': {('portfolio', 'option')},
            },
        ),
    ]
